"""
Django settings for django_tutorial project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import environ

from pathlib import Path

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d7sn5tb59sma3&z^$+0p@@umq9$p^qd-80-=fy%8)pp$idg%%2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sqlserver.apps.SqlServerConfig' # Added the newly created app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_tutorial.wsgi.application'

# Load .env file to retrieve the settings for db connections
ENV_ROOT_DIR = environ.Path(__file__) - 3
READ_DOT_ENV_FILE = env.bool('READ_DOT_ENV_FILE', default=True)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    env.read_env(f'{BASE_DIR}/.sql')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# connection string format: postgres://username:password@Host/db-name
DATABASES = {
    'default': env.db(
        'DATABASE_URL', 
        default='postgres://postgres:postgres@localhost/django_tutorial'), 
}

mssql_host = env('MSSQL_HOST')
mssql_name = env('MSSQL_NAME')
mssql_username = env('MSSQL_USERNAME')
mssql_password = env('MSSQL_PASSWORD')

# Set up mssql_db connection
DATABASES['mssql_db'] = {
    'ENGINE': 'mssql',
    'HOST': mssql_host,
    'NAME': mssql_name,
    'USER': mssql_username,
    'PASSWORD': mssql_password,
    'PORT': '1433',
    'OPTIONS': {
        'driver': 'ODBC Driver 13 for SQL Server'
      }
}
DATABASES['mssql_db']['ATOMIC_REQUESTS'] = True

# Set up db router, with which DB operations depend on
DATABASE_ROUTERS = [
    'sqlserver.router.SqlServerRouter',]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = f'{BASE_DIR}/staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [f'{BASE_DIR}/static']

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login redirection
LOGIN_REDIRECT_URL = "/"
# Logout redirection
LOGOUT_REDIRECT_URL = "/"