# Generated by Django 3.2.15 on 2022-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE',
                # 'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('days_of_attendance', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('days_of_leaves_deductible', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('leaves_deductible_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('health_insurance', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('labor_insurance', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('tax_deduction', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('salary_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('pension', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('supplementary_health_insurance', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'SALARY',
                # 'managed': False,
            },
        ),
    ]
